micronaut:
  server:
    port: 8081
    error:
      include-message: always
  application:
    name: ExamsAPI

datasources:
  default:
    url: jdbc:mysql://localhost:3306/ktSchoolExams
    username: henriquecarmo
    password: MySQLTest!
    driverClassName: com.mysql.cj.jdbc.Driver
    dialect: org.hibernate.dialect.MySQL5InnoDBDialect


jpa:
  default:
    entity-scan:
      packages: 'com.schoolexams'
    properties:
      hibernate:
        hbm2ddl:
          auto: create-drop
        show_sql: true
        format_sql: true

io:
  micronaut:
    context:
      condition: trace


